import type { UpgradeDef } from './types';

export const UPGRADES: readonly UpgradeDef[] = [
  // click upgrades
  { id: 'stronger-grip',  name: 'Stronger Grip',  description: 'Quests yield twice the gold.',      icon: '✊', realmId: 'verdant', cost: { gold: 100 },          effect: { target: 'click', multiplier: 2 } },
  { id: 'quest-board',    name: 'Quest Board',    description: 'Quests yield twice the gold.',      icon: '📋', realmId: 'verdant', cost: { gold: 10000 },        effect: { target: 'click', multiplier: 2 }, requires: 'stronger-grip' },
  { id: 'guild-banner',   name: 'Guild Banner',   description: 'Quests yield twice the gold.',      icon: '🚩', realmId: 'verdant', cost: { gold: 1000000 },      effect: { target: 'click', multiplier: 2 }, requires: 'quest-board' },
  { id: 'royal-charter',  name: 'Royal Charter',  description: 'Quests yield twice the gold.',      icon: '📜', realmId: 'verdant', cost: { gold: 100000000 },    effect: { target: 'click', multiplier: 2 }, requires: 'guild-banner' },
  // hero upgrades, tier 1
  { id: 'iron-pitchforks',  name: 'Iron Pitchforks',  description: 'Farmhands are twice as effective.',     icon: '🔱', realmId: 'verdant', cost: { gold: 500 },           effect: { target: 'hero:farmhand', multiplier: 2 } },
  { id: 'squire-training',  name: 'Squire Training',  description: 'Squires are twice as effective.',       icon: '🎯', realmId: 'verdant', cost: { gold: 2500 },          effect: { target: 'hero:squire', multiplier: 2 } },
  { id: 'sharp-swords',     name: 'Sharp Swords',     description: 'Warriors are twice as effective.',      icon: '🗡️', realmId: 'verdant', cost: { gold: 5000 },          effect: { target: 'hero:warrior', multiplier: 2 } },
  { id: 'longbows',         name: 'Longbows',         description: 'Archers are twice as effective.',       icon: '🪶', realmId: 'verdant', cost: { gold: 60000 },         effect: { target: 'hero:archer', multiplier: 2 } },
  { id: 'spellbooks',       name: 'Spellbooks',       description: 'Mages are twice as effective.',         icon: '📖', realmId: 'verdant', cost: { gold: 650000 },        effect: { target: 'hero:mage', multiplier: 2 } },
  { id: 'holy-blades',      name: 'Holy Blades',      description: 'Paladins are twice as effective.',      icon: '⚜️', realmId: 'verdant', cost: { gold: 7000000 },       effect: { target: 'hero:paladin', multiplier: 2 } },
  { id: 'dragon-saddles',   name: 'Dragon Saddles',   description: 'Dragon Tamers are twice as effective.', icon: '🪑', realmId: 'verdant', cost: { gold: 100000000 },     effect: { target: 'hero:dragontamer', multiplier: 2 } },
  { id: 'arcane-tomes',     name: 'Arcane Tomes',     description: 'Archmages are twice as effective.',     icon: '🌌', realmId: 'verdant', cost: { gold: 1650000000 },    effect: { target: 'hero:archmage', multiplier: 2 } },
  // click synergy: kliks schalen mee met productie, zodat actief spelen blijft lonen
  { id: 'joint-quests',        name: 'Joint Quests',        description: 'Heroes join your quests: +2% of your gold/s per quest.', icon: '🤝', realmId: 'verdant', cost: { gold: 75000 },      effect: { target: 'click-synergy', percentOfProduction: 2 } },
  { id: 'war-councils',        name: 'War Councils',        description: 'Quests grant another 3% of your gold/s.',             icon: '🗺️', realmId: 'verdant', cost: { gold: 8000000 },    effect: { target: 'click-synergy', percentOfProduction: 3 }, requires: 'joint-quests' },
  { id: 'legendary-campaigns', name: 'Legendary Campaigns', description: 'Quests grant another 5% of your gold/s.',             icon: '🏅', realmId: 'verdant', cost: { gold: 1000000000 }, effect: { target: 'click-synergy', percentOfProduction: 5 }, requires: 'war-councils' },
  // critical quests
  { id: 'lucky-strikes',       name: 'Lucky Strikes',       description: '5% chance a quest crits for 10× gold.',                 icon: '🍀', realmId: 'verdant', cost: { gold: 400000 },     effect: { target: 'click-crit', chance: 0.05, critMultiplier: 10 } },
  { id: 'heroic-strikes',      name: 'Heroic Strikes',      description: 'Crit chance doubles to 10%, crits hit for 20×.',        icon: '💥', realmId: 'verdant', cost: { gold: 40000000 },   effect: { target: 'click-crit', chance: 0.05, critMultiplier: 20 }, requires: 'lucky-strikes' },
  // click combo: snel doorklikken bouwt heat op (UI-state, nooit opgeslagen) tot dit maximum
  { id: 'battle-rhythm',       name: 'Battle Rhythm',       description: 'Chain quests quickly to build a combo, up to ×2 gold.', icon: '🥁', realmId: 'verdant', cost: { gold: 200000 },     effect: { target: 'click-combo', maxMultiplier: 2 } },
  { id: 'battle-frenzy',       name: 'Battle Frenzy',       description: 'Your combo now climbs all the way to ×3 gold.',         icon: '🔥', realmId: 'verdant', cost: { gold: 20000000 },   effect: { target: 'click-combo', maxMultiplier: 3 }, requires: 'battle-rhythm' },
  // auto-quests: ingehuurd personeel klikt voor je (telt als gewone quests, géén combo-heat)
  { id: 'quest-herald',        name: 'Quest Herald',        description: 'A herald runs 1 quest every second for you.',           icon: '📯', realmId: 'verdant', cost: { gold: 2000000 },    effect: { target: 'auto-click', clicksPerSecond: 1 } },
  { id: 'guild-steward',       name: 'Guild Steward',       description: 'Your steward steps in: 3 quests every second.',         icon: '🗝️', realmId: 'verdant', cost: { gold: 150000000 },  effect: { target: 'auto-click', clicksPerSecond: 3 }, requires: 'quest-herald' },
  { id: 'royal-envoy',         name: 'Royal Envoy',         description: 'The royal envoy commands 6 quests every second.',       icon: '🏇', realmId: 'verdant', cost: { gold: 10000000000 }, effect: { target: 'auto-click', clicksPerSecond: 6 }, requires: 'guild-steward' },
  // hero upgrades, tier 2
  { id: 'steel-pitchforks', name: 'Steel Pitchforks', description: 'Farmhands are twice as effective.',     icon: '🔱', realmId: 'verdant', cost: { gold: 25000 },         effect: { target: 'hero:farmhand', multiplier: 2 }, requires: 'iron-pitchforks' },
  { id: 'squire-armor',     name: 'Squire Armor',     description: 'Squires are twice as effective.',       icon: '🦺', realmId: 'verdant', cost: { gold: 125000 },        effect: { target: 'hero:squire', multiplier: 2 }, requires: 'squire-training' },
  { id: 'battle-tactics',   name: 'Battle Tactics',   description: 'Warriors are twice as effective.',      icon: '♟️', realmId: 'verdant', cost: { gold: 250000 },        effect: { target: 'hero:warrior', multiplier: 2 }, requires: 'sharp-swords' },
  { id: 'eagle-eyes',       name: 'Eagle Eyes',       description: 'Archers are twice as effective.',       icon: '🦅', realmId: 'verdant', cost: { gold: 3000000 },       effect: { target: 'hero:archer', multiplier: 2 }, requires: 'longbows' },
  { id: 'mana-crystals',    name: 'Mana Crystals',    description: 'Mages are twice as effective.',         icon: '💎', realmId: 'verdant', cost: { gold: 32500000 },      effect: { target: 'hero:mage', multiplier: 2 }, requires: 'spellbooks' },
  { id: 'sacred-oaths',     name: 'Sacred Oaths',     description: 'Paladins are twice as effective.',      icon: '🕊️', realmId: 'verdant', cost: { gold: 350000000 },     effect: { target: 'hero:paladin', multiplier: 2 }, requires: 'holy-blades' },
  { id: 'elder-dragons',    name: 'Elder Dragons',    description: 'Dragon Tamers are twice as effective.', icon: '🐲', realmId: 'verdant', cost: { gold: 5000000000 },    effect: { target: 'hero:dragontamer', multiplier: 2 }, requires: 'dragon-saddles' },
  { id: 'reality-weaving',  name: 'Reality Weaving',  description: 'Archmages are twice as effective.',     icon: '🌀', realmId: 'verdant', cost: { gold: 82500000000 },   effect: { target: 'hero:archmage', multiplier: 2 }, requires: 'arcane-tomes' },
  // hero upgrades, tier 3 — de late-game grind: tier 2 × 50
  { id: 'mythril-pitchforks', name: 'Mythril Pitchforks', description: 'Farmhands are twice as effective.',     icon: '🔱', realmId: 'verdant', cost: { gold: 1250000 },        effect: { target: 'hero:farmhand', multiplier: 2 }, requires: 'steel-pitchforks' },
  { id: 'squire-knighthood',  name: 'Squire Knighthood',  description: 'Squires are twice as effective.',       icon: '🛡️', realmId: 'verdant', cost: { gold: 6250000 },        effect: { target: 'hero:squire', multiplier: 2 }, requires: 'squire-armor' },
  { id: 'war-veterans',       name: 'War Veterans',       description: 'Warriors are twice as effective.',      icon: '🎖️', realmId: 'verdant', cost: { gold: 12500000 },       effect: { target: 'hero:warrior', multiplier: 2 }, requires: 'battle-tactics' },
  { id: 'storm-arrows',       name: 'Storm Arrows',       description: 'Archers are twice as effective.',       icon: '🌩️', realmId: 'verdant', cost: { gold: 150000000 },      effect: { target: 'hero:archer', multiplier: 2 }, requires: 'eagle-eyes' },
  { id: 'archlich-pacts',     name: 'Archlich Pacts',     description: 'Mages are twice as effective.',         icon: '💀', realmId: 'verdant', cost: { gold: 1625000000 },     effect: { target: 'hero:mage', multiplier: 2 }, requires: 'mana-crystals' },
  { id: 'angelic-blessings',  name: 'Angelic Blessings',  description: 'Paladins are twice as effective.',      icon: '👼', realmId: 'verdant', cost: { gold: 17500000000 },    effect: { target: 'hero:paladin', multiplier: 2 }, requires: 'sacred-oaths' },
  { id: 'dragon-bonds',       name: 'Dragon Bonds',       description: 'Dragon Tamers are twice as effective.', icon: '🔥', realmId: 'verdant', cost: { gold: 250000000000 },   effect: { target: 'hero:dragontamer', multiplier: 2 }, requires: 'elder-dragons' },
  { id: 'cosmic-attunement',  name: 'Cosmic Attunement',  description: 'Archmages are twice as effective.',     icon: '☄️', realmId: 'verdant', cost: { gold: 4125000000000 },  effect: { target: 'hero:archmage', multiplier: 2 }, requires: 'reality-weaving' },
  // nieuwe helden, tier 1 + 2 (basis ×5, daarna ×50)
  { id: 'runic-armor',        name: 'Runic Armor',        description: 'Titans are twice as effective.',        icon: '🗿', realmId: 'verdant', cost: { gold: 2000000000000 },   effect: { target: 'hero:titan', multiplier: 2 } },
  { id: 'mountain-hearts',    name: 'Mountain Hearts',    description: 'Titans are twice as effective.',        icon: '⛰️', realmId: 'verdant', cost: { gold: 100000000000000 }, effect: { target: 'hero:titan', multiplier: 2 }, requires: 'runic-armor' },
  { id: 'divine-sparks',      name: 'Divine Sparks',      description: 'Demigods are twice as effective.',      icon: '⚡', realmId: 'verdant', cost: { gold: 50000000000000 },  effect: { target: 'hero:demigod', multiplier: 2 } },
  { id: 'godhood-trials',     name: 'Godhood Trials',     description: 'Demigods are twice as effective.',      icon: '🌟', realmId: 'verdant', cost: { gold: 2500000000000000 }, effect: { target: 'hero:demigod', multiplier: 2 }, requires: 'divine-sparks' },
  { id: 'starfire-wings',     name: 'Starfire Wings',     description: 'Celestials are twice as effective.',    icon: '🌠', realmId: 'verdant', cost: { gold: 25000000000000000 }, effect: { target: 'hero:celestial', multiplier: 2 } },
  { id: 'songs-of-creation',  name: 'Songs of Creation',  description: 'Celestials are twice as effective.',    icon: '🎶', realmId: 'verdant', cost: { gold: 1250000000000000000 }, effect: { target: 'hero:celestial', multiplier: 2 }, requires: 'starfire-wings' },
  // volgende tiers voor de actieve mechanics
  { id: 'imperial-mandate',   name: 'Imperial Mandate',   description: 'Quests yield twice the gold.',           icon: '🏛️', realmId: 'verdant', cost: { gold: 10000000000 },   effect: { target: 'click', multiplier: 2 }, requires: 'royal-charter' },
  { id: 'eternal-crusades',   name: 'Eternal Crusades',   description: 'Quests grant another 7% of your gold/s.', icon: '⚔️', realmId: 'verdant', cost: { gold: 100000000000 },  effect: { target: 'click-synergy', percentOfProduction: 7 }, requires: 'legendary-campaigns' },
  { id: 'divine-strikes',     name: 'Divine Strikes',     description: 'Crit chance grows to 15%, crits hit for 30×.', icon: '✨', realmId: 'verdant', cost: { gold: 8000000000 }, effect: { target: 'click-crit', chance: 0.05, critMultiplier: 30 }, requires: 'heroic-strikes' },
  { id: 'battle-trance',      name: 'Battle Trance',      description: 'Your combo now surges all the way to ×4 gold.', icon: '🌪️', realmId: 'verdant', cost: { gold: 4000000000 }, effect: { target: 'click-combo', maxMultiplier: 4 }, requires: 'battle-frenzy' },
  { id: 'war-marshal',        name: 'War Marshal',        description: 'The war marshal commands 12 quests every second.', icon: '🎺', realmId: 'verdant', cost: { gold: 2000000000000 }, effect: { target: 'auto-click', clicksPerSecond: 12 }, requires: 'royal-envoy' },
] as const;
